server:
  port: 3000

spring:
  jmx:
    enabled: true

  main:
    allow-bean-definition-overriding: true
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-ui